### ISSUE TITLE
MaplyScreenMarker offset property does not seem to have any effect

### ISSUE THREAD

**Issue by JesseCrocker** [mousebird/WhirlyGlobe#141]
MaplyScreenMarker images seems to be displayed centered on the coordinate, I would expect the offset property to change where the image is anchored, but it doesn't seem to have an effect.

Adding 2 markers, one with marker.offset = CGPointMake(0, -40), and one with no offset, and the images are both in the same location.

Am i doing something wrong here, or is this a bug?

**Comment by mousebird** [comment]
Fixed.

**Comment by JubrilO** [comment]
I'm still having this issue where setting an offset has no effect. I have tried setting the layout importance to MAXFLOAT as suggested above but it makes no difference.

Was this fix implemented on the Master branch or should I be using another branch?

**Comment by mousebird** [comment]
You might try develop.

**Comment by JubrilO** [comment]
I just tried the develop branch, the issue persists.

**Comment by mousebird** [comment]
I just ran a test with markers like this:
                // Marker for reference
                let marker = MaplyScreenMarker()
                marker.loc = object.center()
                marker.layoutImportance = MAXFLOAT
                marker.size = CGSize(width: 4.0, height: 4.0)
                marker.offset = CGPoint(x: -32.0, y: 0.0)

Worked just fine.  The marker appeared to the left of it's original position.
