### ISSUE TITLE
kMaplyWideVecJoinType modes are all buggy

### ISSUE THREAD

**Issue by JesseCrocker** [mousebird/WhirlyGlobe#357]
![miter](https://cloud.githubusercontent.com/assets/2048291/8875434/6b2b4d3c-31d6-11e5-8583-5bda199b59e7.jpg)
![round-join](https://cloud.githubusercontent.com/assets/2048291/8875438/6f6a8aa2-31d6-11e5-9d11-734f18a19eb7.jpg)
![bevel](https://cloud.githubusercontent.com/assets/2048291/8875446/78d1d2d0-31d6-11e5-8923-40684b3631a1.jpg)

**Comment by mousebird** [comment]
Round joins aren't implemented.  I've updated the constants to reflect that.

I suspect you've got parallel lines in the first case and I'm not clear on why the third case is bad.

Can you dump out the coordinates and description dictionaries for the first and third cases?

-thanks

**Comment by JesseCrocker** [comment]
Yeah, the first case is parallel lines. I'll replicate 1 and 3 in the test app.

**Comment by JesseCrocker** [comment]
https://github.com/trailbehind/WhirlyGlobe/tree/testcase/line-joins 
![screen shot 2015-08-06 at 11 22 09 am](https://cloud.githubusercontent.com/assets/2048291/9118440/9d18905a-3c2d-11e5-8d15-69ac00aa4764.png)

**Comment by mousebird** [comment]
Nice test cases, thanks.

These should both be fixed now.

**Comment by JesseCrocker** [comment]
Those might be fixed, but for almost overlapping lines with kMaplyWideVecMiterJoin there is now a weird artifact that moves away from the vertex with the join.
![screenshot_8_7_15__8_26_am](https://cloud.githubusercontent.com/assets/2048291/9137978/893a0c9c-3cde-11e5-9ab3-e88e4d1c34b7.jpg)
![screenshot_8_7_15__8_27_am](https://cloud.githubusercontent.com/assets/2048291/9137983/8e95d342-3cde-11e5-993f-0a329931c4dd.jpg)
![screenshot_8_7_15__8_27_am 2](https://cloud.githubusercontent.com/assets/2048291/9137985/91853f34-3cde-11e5-87cf-35140e6671dc.jpg)

**Comment by JesseCrocker** [comment]
Here's another testcase showing weird disconnected artifacts. These artifacts are not new with yesterdays changes. https://github.com/trailbehind/WhirlyGlobe/tree/testcase/wide-vectors-small-angles

The black line is a regular vector, the red line is a wide vector
![ios_simulator_-_iphone_6_-_iphone_6___ios_8_4__12h141_](https://cloud.githubusercontent.com/assets/2048291/9138039/d521c76c-3cde-11e5-9d29-c8aa63fb3b3f.jpg)

**Comment by mousebird** [comment]
There's a lot of weirdness going there in the bevel case.  I'll dig into this early next week.

**Comment by mousebird** [comment]
Should be fixed.  Let me know if your other test cases are still in good shape.

**Comment by JesseCrocker** [comment]
That made things way worse, lots of lines shooting off hundreds of pixels from vertices.

**Comment by mousebird** [comment]
In the test case or with other data?  I was using your test case to debug this.

**Comment by JesseCrocker** [comment]
With real gps tracks.

**Comment by mousebird** [comment]
Something weird happened with the merge and I see you had your own changes.
I'll check this against the develop branch with your test data.
Care to contribute a couple more tracks to put in the test app?

**Comment by mousebird** [comment]
I pulled your geojson example into the develop tree.  Had to fix the GeoJSON parser, incidentally, so you must have some local changes.

Anyway, this is what I got.  I suspect there are some custom changes in your own tree.

![screen shot 2015-09-04 at 2 32 27 pm](https://cloud.githubusercontent.com/assets/1040005/9694966/262aa61c-5312-11e5-8cf0-0e35eacd546d.png)

**Comment by mousebird** [comment]
I think this was a local branch problem.  Please reopen if it happens with the current source tree.  Otherwise I think it's fixed in the current develop branch.

**Comment by JesseCrocker** [comment]
It was not a local branch problem. I can still get it to produce crazy results with the current develop branch. I'll post some more test cases later today.

**Comment by JesseCrocker** [comment]
I added a couple more test cases at https://github.com/trailbehind/WhirlyGlobe/tree/testcase/line-joins-2015-09-11 Or if you just want to grab a geojson file https://gist.github.com/JesseCrocker/a4681018dedefabf45a7 shows the main problem im seeing now. 
![screen shot 2015-09-11 at 11 03 17 am](https://cloud.githubusercontent.com/assets/2048291/9821010/b9a2c0f2-5874-11e5-9aac-f794be56f570.png)

**Comment by mousebird** [comment]
This one is tricky to fix.  Basically, the lines don't work zoomed out that far.  They're close enough that the screen sized width can't form valid junctions.  You'll see they snap into place if you zoom in far enough.

I think I'll detect the scale this happens at and then turn off the junctions past that point.  Then we'll need a separate set of segments that pop in at the same time.  Otherwise you'll see nothing when the junctions turn off.

**Comment by JesseCrocker** [comment]
Yeah, that sawtooth case is tricky. We simplify lines to eliminate any vertices that move the line less than 1px(using Ramer–Douglas–Peucker) before creating the MaplyVectorObject, but cases like that don't simplify at all.

**Comment by mousebird** [comment]
I've added a change to turn off the junctions when they start to exceed the length of their nearby segments.  So when you zoom out here, the extra lines should just disappear.

Give the a whirl and let me know if it's good enough.  The next step, I think, would be adding a second set of lines that turn on when the junctions are going to fail.

**Comment by JesseCrocker** [comment]
That seems to work, no more lines shooting off the joins, just gaps in the lines. What involved in getting rid of the gaps?

**Comment by mousebird** [comment]
We'd need to make two versions of the segments between.  One that's active when the junctions are valid and one that's active when they're not.

That will make everything much bigger, so I'd probably want to turn it off by default.

It's a teensy bit outside the scope of just a bug fix.  What's happening here is that the lines aren't really valid at the scale they're being displayed.  With vector tiles, we'd just have a different version zoomed out.  Obviously not that helpful in your case.

**Comment by JesseCrocker** [comment]
So it sounds like maybe we just need to be simplifying the lines differently? We're not just displaying the raw geometries on screen, they get resimplified every 3 zoom levels.

This same thing will happen with vector tiles, it just doesn't because lines in the vector tiles aren't usually using wide vectors.

**Comment by mousebird** [comment]
The safest thing is to add that mode with the two different versions.  I guess I'm saying it's not a bug fix, but I'd be willing to add it and let you turn it on.  It would probably only take a few hours.

I don't want it on by default because it'll slow down regular vector tiles, but it'll be perfect for your cse.

**Comment by mousebird** [comment]
Thinking about simplification, you'd want to look for cases where two adjoining segments get within 2*width of each other.  When they do, you could cut them at that point.  That would get you the same thing I was talking about, but cheaper.

**Comment by JesseCrocker** [comment]
Thinking about it more, I don't think I could really work around this with line simplification, because it wouldn't just require simplifying, it requires combining parallel lines.  


![untitled 4](https://cloud.githubusercontent.com/assets/2048291/10174674/49350ae0-66a8-11e5-9b5c-e56cbe3bbbf1.png)
In this case the circled part either has to be removed completely, or collapsed to a a single line instead of 2 parallel lines, and there would be lots of other edge cases.

**Comment by mousebird** [comment]
Yup, you got it.  But it's an easy fix.  You just break the line right at that middle point.  Then you get two separate lines, which is exactly what I was going to do.

**Comment by mousebird** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;boICE4ij&#x2F;47-github-issues"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Github issues</a>

**Comment by mousebird** [comment]
Should now be fixed in the feature/widen-update branch.  Dashed lines also work pretty well now too, at least for normal cases.

Could be optimized a bit more.  Too many vertices in some cases.  But for now, I think it's good enough.

Give it a try and let me know what you find.

**Comment by JesseCrocker** [comment]
It looks like MaplyLinearTextureBuilder has some significant changes.
It no longer has an opacityFunc property. Is this no longer needed, or is there some replacement for it?
The initialized no longer takes a size parameter, and size is initialized to zero.

Does my code need any changes other than no longer setting those values?

**Comment by JesseCrocker** [comment]
Dashed lines still don't work right close to parallel.
![screen shot 2016-01-12 at 6 04 40 am](https://cloud.githubusercontent.com/assets/2048291/12264217/6bf5c6d6-b8f2-11e5-9417-9d5b41719de4.png)

**Comment by mousebird** [comment]
The MaplyLinearTextureBuilder is much simpler now.  It only needs the pattern and it'll figure out the rest.  The opacity dropoff is implemented in the fragment shader now, so there's no need for a 2D texture.  The MaplyLinearTextureBuilder just implements a 1D texture for the dot-dash pattern.

As for the dash problem, can I get that path as a test case?

**Comment by JesseCrocker** [comment]
https://github.com/trailbehind/WhirlyGlobe/tree/testcase/uturn-dashes

**Comment by mousebird** [comment]
Try out the latest feature/widen-update.

I'm breaking acute angles.  That seems to help.

The texture coordinates are getting wonky on long stretches of geometry.  There's an option in there for TEXTURE_RESET.  Give that a try and see if you like it better than the default.  It cuts the problem down a bit, but breaks the spirals at low zoom levels.

**Comment by mousebird** [comment]
It's all coming down to floating point resolution.  Some lines are getting long enough that the distance we're putting into the texture coordinate calculation gets too big.

Breaking up the calculation might help, for a while at least.  You can always zoom really far in on an enormous line segment.

In any case, try out the current version.  The geometry should all be right and the texture application right until the numbers get too big.

**Comment by mousebird** [comment]
I think there will be more issues in the future, but let's put this one to bed.
