### ISSUE TITLE
Get all objects in selected location

### ISSUE THREAD

**Issue by amirfl** [mousebird/WhirlyGlobe#801]
Is there a way to get all objects (instead of just a single object) that are tapped over by the user. 
I have a few overlapping regions, shown as vector objects on the globe. When the user taps them I'd like to show a menu where he can select the object interested in.

**Comment by mousebird** [comment]
Use the allSelect: delegate instead.

**Comment by amirfl** [comment]
Thanks. I've implemented 
`- (void)globeViewController:(WhirlyGlobeViewController *)viewC allSelect:(NSArray *)selectedObjs atLoc:(MaplyCoordinate)coord onScreen:(CGPoint)screenPt`

However, allSelect contains only a single MaplyVectorObject when the user taps on an area with overlapping vectors. I know this method works fine with other objects, because multiple markers are returned when a user taps an area with a close markers.

**Comment by mousebird** [comment]
Make sure you're on a recent version.  I believe we just fixed that a few weeks ago.

**Comment by amirfl** [comment]
Just updated to daily build 108 (latest) for iOS, but unfortunately still getting the same problem.

**Comment by mousebird** [comment]
I'm seeing multiple object selection working in a test case.  I did have to set MaplyVectorObject.selectable = true.

**Comment by amirfl** [comment]
I can get it to work for multiple markers, but not for multiple vectors.
Here is how I create my vector objects:
```
- (void) addVectors {
NSDictionary *sigmetBorderDict = @{
                        kMaplyColor : [UIColor redColor],
                        kMaplySelectable : @(true),
                        kMaplyVecWidth : @(4.0),
                        kMaplyEnable: @(YES),
                        };
dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT,0), ^{
        // iterate through all objects
        NSMutableArray *sigmetObjects = [[NSMutableArray alloc] init];
        
        for (AirSigMet *airSigMet in wxDataStore.AllAirSigMets) {        
            NSData *jsonData = [[airSigMet areaGeoJSON] dataUsingEncoding:NSUTF8StringEncoding];
            if (jsonData) {
                MaplyVectorObject *wgVecObj = [MaplyVectorObject VectorObjectFromGeoJSON:jsonData];
                wgVecObj.userObject = airSigMet;
                wgVecObj.selectable = true;
                 [sigmetObjects addObject:wgVecObj];
            }
        }
        
        // Add the objects to the map 
        if (sigmetObjects && sigmetObjects.count > 0) {
            sigmetObj = [theViewC addVectors:sigmetObjects desc:sigmetBordersDict];
        }
    });
}
```

Here is how I handle the selection:
```
- (void)globeViewController:(WhirlyGlobeViewController *)viewC allSelect:(NSArray *)selectedObjs atLoc:(MaplyCoordinate)coord onScreen:(CGPoint)screenPt{
    
    NSMutableArray *selectedAirSigmets = [[NSMutableArray alloc] init];
    
// selectedObjs.count is always 1, even when tapping on overlapping vectors
    for (int i = 0; i < selectedObjs.count; i++) {
        id selectedObj = [selectedObjs[i] selectedObj];
        NSLog(@"selectedObj class: %@",[selectedObj class]);

        if ([selectedObj isKindOfClass:[MaplyVectorObject class]]) {
            NSLog(@"userObject: %@", [selectedObj userObject]);
            if ([[selectedObj userObject] isKindOfClass:[AirSigMet class]]) {
                AirSigMet *airSigMet = (AirSigMet *)[selectedObj userObject];
                [selectedAirSigmets addObject:airSigMet];
            }
    }

   // Always '1', even when multiple vectors are selected
    NSLog(@"selected airSigmets count: %lu", (unsigned long)selectedAirSigmets.count);
}
```

**Comment by amirfl** [comment]
still having the problem, but worked around it by searching through all my vector objects and testing which ones had the tap location inside their borders.

**Comment by mousebird** [comment]
The test case I built for this appears to work, so I'm not sure what to suggest.
